import java.io.Closeable;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * This class establishes a connection (session) to a specific database.
 * SQL statements  are executed and results are returned within the context of a
 * connection.
 */
public class Connection implements Closeable {
	/**
	 * Attempts to establish a connection to the given database URL.
	 *
	 * @param  url           A database url of the form
	 *                           jdbc:protocol://hostname/database
	 * @param  user          The database user on whose behalf the connection is
	 *                       being made
	 * @param  passwd        The users password
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public Connection(String url, String user, String passwd) throws SQLException {
		con = DriverManager.getConnection(url, user, passwd);
		con.setAutoCommit(true);
	}

	/**
	 * Initiates a transaction.
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public void begin() throws SQLException {
		con.setAutoCommit(false);
	}

	/**
	 * Executes  the SQL query  and returns  the Result object  generated by the
	 * query.
	 *
	 * @param  sql           A SQL statement  that may contain  one or more  '?'
	 *                       parameter placeholders
	 * @param  params        The objects containing the input parameter values
	 *
	 * @return A Result object that contains the data produced by the query
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public Result executeQuery(String sql, Object... params) throws SQLException {
		PreparedStatement stmt = prepare(sql, params);
		try {
			return new Result(stmt);
		}
		catch (SQLException e) {
			try {stmt.close();} catch (SQLException ignore) {}
			throw e;
		}
	}

	/**
	 * Execute an SQL statement and returns the number of affected rows.
	 *
	 * @param  sql           A SQL statement  that may contain  one or more  '?'
	 *                       parameter placeholders
	 * @param  params        The objects containing the input parameter values
	 *
	 * @return Returns the number of rows  that were modified  or deleted by the
	 *         SQL statement.
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public int executeUpdate(String sql, Object... params) throws SQLException {
		PreparedStatement stmt = prepare(sql, params);
		try {
			return stmt.executeUpdate();
		}
		catch (SQLException e) {
			try {stmt.close();} catch (SQLException ignore) {}
			throw e;
		}
	}

	/**
	 * Commits a transaction
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public void commit() throws SQLException {
		con.commit();
		con.setAutoCommit(true);
	}

	/**
	 * Rolls back a transaction
	 *
	 * @throws SQLException  If a database access error occurs
	 */
	public void rollback() throws SQLException {
		con.rollback();
		con.setAutoCommit(true);
	}

	/**
	 * Closes the Connection and releases its resources.
	 *
	 * It is strongly recommended  to explicitly commit  or roll back  an active
	 * transaction prior to calling the close method.
	 */
	@Override
	public void close() {
		try {con.close();} catch (SQLException ignore) {}
	}

	private PreparedStatement prepare(String sql, Object[] params) throws SQLException {
		PreparedStatement stmt = con.prepareStatement(sql);
		try {
			for (int i = 0; i < params.length; ++i) {
				stmt.setObject(i + 1, params[i]);
			}
			return stmt;
		}
		catch (SQLException e) {
			try {stmt.close();} catch (SQLException ignore) {}
			throw e;
		}
	}

	private java.sql.Connection con;
}
